-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_env_vars (
  id uuid NOT NULL,
  app_id uuid NOT NULL,
  key text NOT NULL,
  encrypted_value text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT app_env_vars_pkey PRIMARY KEY (id),
  CONSTRAINT app_env_vars_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps(id)
);
CREATE TABLE public.app_metrics (
  id uuid NOT NULL,
  app_id uuid NOT NULL,
  cpu_seconds numeric NOT NULL DEFAULT 0,
  memory_used_bytes bigint,
  container_status text,
  restarts integer NOT NULL DEFAULT 0,
  request_count bigint,
  error_count bigint,
  network_rx_bytes bigint NOT NULL DEFAULT 0,
  network_tx_bytes bigint NOT NULL DEFAULT 0,
  log_bytes bigint,
  uptime_seconds bigint,
  collected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT app_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT app_metrics_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps(id)
);
CREATE TABLE public.apps (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  node_id uuid,
  name text NOT NULL,
  type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'created'::"AppStatus",
  container_name text,
  image_ref text,
  cpu_limit numeric,
  memory_limit_bytes bigint,
  disk_limit_bytes bigint,
  default_domain text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  last_started_at timestamp with time zone,
  restart_count integer NOT NULL DEFAULT 0,
  CONSTRAINT apps_pkey PRIMARY KEY (id),
  CONSTRAINT apps_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT apps_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL,
  actor_user_id uuid,
  actor_type USER-DEFINED NOT NULL,
  action text NOT NULL,
  target_type text,
  target_id uuid,
  ip_address text,
  user_agent text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.backup_storage_providers (
  id uuid NOT NULL,
  name text NOT NULL,
  provider text NOT NULL,
  endpoint text,
  region text,
  bucket text,
  prefix text,
  access_key_encrypted text,
  secret_key_encrypted text,
  local_path text,
  retention_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'active'::text,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT backup_storage_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.build_metrics (
  id uuid NOT NULL,
  deployment_id uuid NOT NULL,
  duration_seconds integer,
  cpu_seconds numeric NOT NULL DEFAULT 0,
  memory_peak_bytes bigint,
  log_bytes bigint,
  status USER-DEFINED NOT NULL,
  failure_reason text,
  collected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT build_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT build_metrics_deployment_id_fkey FOREIGN KEY (deployment_id) REFERENCES public.deployments(id)
);
CREATE TABLE public.cms_marketing_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text,
  title text NOT NULL,
  slug text NOT NULL,
  excerpt text,
  content_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  content_html text,
  seo_title text,
  seo_description text,
  og_image_url text,
  canonical_url text,
  author_id uuid,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT cms_marketing_pages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.control_plane_backups (
  id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::"BackupStatus",
  storage_provider text NOT NULL,
  backup_storage_provider_id uuid,
  storage_path text NOT NULL,
  size_bytes bigint,
  checksum text,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT control_plane_backups_pkey PRIMARY KEY (id),
  CONSTRAINT control_plane_backups_backup_storage_provider_id_fkey FOREIGN KEY (backup_storage_provider_id) REFERENCES public.backup_storage_providers(id)
);
CREATE TABLE public.database_backups (
  id uuid NOT NULL,
  database_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::"BackupStatus",
  backup_type USER-DEFINED NOT NULL DEFAULT 'logical'::"BackupType",
  storage_provider text NOT NULL,
  backup_storage_provider_id uuid,
  storage_path text NOT NULL,
  size_bytes bigint,
  checksum text,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT database_backups_pkey PRIMARY KEY (id),
  CONSTRAINT database_backups_database_id_fkey FOREIGN KEY (database_id) REFERENCES public.databases(id),
  CONSTRAINT database_backups_backup_storage_provider_id_fkey FOREIGN KEY (backup_storage_provider_id) REFERENCES public.backup_storage_providers(id)
);
CREATE TABLE public.database_clusters (
  id uuid NOT NULL,
  name text NOT NULL,
  provider_id uuid,
  node_id uuid,
  engine text NOT NULL DEFAULT 'postgres'::text,
  engine_version text,
  admin_connection_encrypted text NOT NULL,
  host text NOT NULL,
  port integer NOT NULL DEFAULT 5432,
  default_database text NOT NULL DEFAULT 'postgres'::text,
  ssl_required boolean NOT NULL DEFAULT false,
  max_databases integer,
  max_storage_bytes bigint,
  current_databases integer NOT NULL DEFAULT 0,
  current_storage_bytes bigint NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text,
  region text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT database_clusters_pkey PRIMARY KEY (id),
  CONSTRAINT database_clusters_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.infrastructure_providers(id),
  CONSTRAINT database_clusters_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.database_imports (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  database_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::"DatabaseImportStatus",
  source_engine text NOT NULL DEFAULT 'postgres'::text,
  source_url_encrypted text,
  save_source_credentials boolean NOT NULL DEFAULT false,
  target_db_name text NOT NULL,
  size_bytes bigint,
  logs text,
  error_code text,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT database_imports_pkey PRIMARY KEY (id),
  CONSTRAINT database_imports_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT database_imports_database_id_fkey FOREIGN KEY (database_id) REFERENCES public.databases(id)
);
CREATE TABLE public.database_metrics (
  id uuid NOT NULL,
  database_id uuid NOT NULL,
  size_bytes bigint NOT NULL DEFAULT 0,
  active_connections integer,
  connection_limit integer,
  network_rx_bytes bigint NOT NULL DEFAULT 0,
  network_tx_bytes bigint NOT NULL DEFAULT 0,
  slow_query_count integer,
  collected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT database_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT database_metrics_database_id_fkey FOREIGN KEY (database_id) REFERENCES public.databases(id)
);
CREATE TABLE public.databases (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  node_id uuid,
  name text NOT NULL,
  engine text NOT NULL DEFAULT 'postgres'::text,
  engine_version text,
  status USER-DEFINED NOT NULL DEFAULT 'provisioning'::"DatabaseStatus",
  db_name text NOT NULL,
  db_user text NOT NULL,
  encrypted_password text NOT NULL,
  storage_limit_bytes bigint NOT NULL,
  current_size_bytes bigint NOT NULL DEFAULT 0,
  connection_limit integer DEFAULT 10,
  database_cluster_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  ssl_mode text NOT NULL DEFAULT 'prefer'::text,
  CONSTRAINT databases_pkey PRIMARY KEY (id),
  CONSTRAINT databases_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT databases_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id),
  CONSTRAINT databases_database_cluster_id_fkey FOREIGN KEY (database_cluster_id) REFERENCES public.database_clusters(id)
);
CREATE TABLE public.deployments (
  id uuid NOT NULL,
  app_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::"DeploymentStatus",
  source_type USER-DEFINED NOT NULL,
  repo_url text,
  branch text,
  commit_sha text,
  build_command text,
  start_command text,
  output_dir text,
  build_node_id uuid,
  runtime_node_id uuid,
  image_ref text,
  error_message text,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT deployments_pkey PRIMARY KEY (id),
  CONSTRAINT deployments_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps(id),
  CONSTRAINT deployments_build_node_id_fkey FOREIGN KEY (build_node_id) REFERENCES public.nodes(id),
  CONSTRAINT deployments_runtime_node_id_fkey FOREIGN KEY (runtime_node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.domains (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  app_id uuid,
  domain text NOT NULL,
  type USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::"DomainStatus",
  verification_token text,
  ssl_status text DEFAULT 'pending'::text,
  target_node_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT domains_pkey PRIMARY KEY (id),
  CONSTRAINT domains_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT domains_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps(id),
  CONSTRAINT domains_target_node_id_fkey FOREIGN KEY (target_node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.email_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  provider text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  from_email text NOT NULL,
  from_name text NOT NULL,
  reply_to_email text,
  api_url text NOT NULL,
  encrypted_api_key text,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_verification_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  email text NOT NULL,
  token_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  consumed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT email_verification_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.feature_overrides (
  id uuid NOT NULL,
  scope_type USER-DEFINED NOT NULL,
  scope_id uuid NOT NULL,
  feature_key text NOT NULL,
  enabled boolean NOT NULL,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  reason text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp with time zone,
  CONSTRAINT feature_overrides_pkey PRIMARY KEY (id)
);
CREATE TABLE public.infrastructure_providers (
  id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  provider text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  region text,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  encrypted_credentials text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT infrastructure_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL,
  organization_id uuid,
  project_id uuid,
  email text NOT NULL,
  role USER-DEFINED NOT NULL,
  token_hash text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::"InvitationStatus",
  invited_by uuid,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT invitations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL,
  type text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::"JobStatus",
  priority integer NOT NULL DEFAULT 100,
  queue text NOT NULL DEFAULT 'default'::text,
  required_worker_type text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 5,
  locked_by text,
  locked_at timestamp with time zone,
  run_after timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  error_message text,
  result jsonb,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.limit_overrides (
  id uuid NOT NULL,
  scope_type USER-DEFINED NOT NULL,
  scope_id uuid NOT NULL,
  limit_key text NOT NULL,
  limit_value bigint,
  enabled boolean,
  reason text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp with time zone,
  CONSTRAINT limit_overrides_pkey PRIMARY KEY (id)
);
CREATE TABLE public.login_events (
  id uuid NOT NULL,
  user_id uuid,
  email text NOT NULL,
  provider USER-DEFINED NOT NULL DEFAULT 'password'::"AuthProvider",
  success boolean NOT NULL,
  reason text,
  ip_address text,
  user_agent text,
  app text NOT NULL DEFAULT 'userapp'::text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT login_events_pkey PRIMARY KEY (id),
  CONSTRAINT login_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.metric_rollups (
  id uuid NOT NULL,
  period USER-DEFINED NOT NULL,
  bucket_start timestamp with time zone NOT NULL,
  scope_type text NOT NULL,
  scope_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
  metric_type text NOT NULL,
  sum bigint NOT NULL DEFAULT 0,
  min bigint,
  max bigint,
  avg numeric,
  samples integer NOT NULL DEFAULT 0,
  unit text NOT NULL DEFAULT 'count'::text,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT metric_rollups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.migrations (
  id uuid NOT NULL,
  project_id uuid,
  resource_type USER-DEFINED NOT NULL,
  resource_id uuid,
  source_node_id uuid,
  target_node_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::"MigrationStatus",
  strategy USER-DEFINED NOT NULL,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT migrations_pkey PRIMARY KEY (id),
  CONSTRAINT migrations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT migrations_source_node_id_fkey FOREIGN KEY (source_node_id) REFERENCES public.nodes(id),
  CONSTRAINT migrations_target_node_id_fkey FOREIGN KEY (target_node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.node_connection_logs (
  id uuid NOT NULL,
  node_id uuid NOT NULL,
  action text NOT NULL,
  status text NOT NULL,
  exit_code integer,
  command text,
  output text,
  error text,
  duration_ms integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT node_connection_logs_pkey PRIMARY KEY (id),
  CONSTRAINT node_connection_logs_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.node_disk_mounts (
  id uuid NOT NULL,
  node_id uuid NOT NULL,
  mount_point text NOT NULL,
  device text,
  fs_type text,
  total_bytes bigint NOT NULL DEFAULT 0,
  used_bytes bigint NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT node_disk_mounts_pkey PRIMARY KEY (id),
  CONSTRAINT node_disk_mounts_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.node_hardware_snapshots (
  id uuid NOT NULL,
  node_id uuid NOT NULL,
  cpu_model text,
  cpu_cores integer,
  cpu_threads integer,
  ram_bytes bigint,
  disk_bytes bigint,
  os_name text,
  os_version text,
  kernel_version text,
  architecture text,
  docker_installed boolean NOT NULL DEFAULT false,
  docker_version text,
  public_ip text,
  private_ip text,
  uptime_seconds bigint,
  raw jsonb NOT NULL DEFAULT '{}'::jsonb,
  collected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT node_hardware_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT node_hardware_snapshots_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.node_metrics (
  id uuid NOT NULL,
  node_id uuid NOT NULL,
  cpu_usage_percent numeric,
  ram_used_bytes bigint,
  disk_used_bytes bigint,
  network_rx_bytes bigint,
  network_tx_bytes bigint,
  collected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  containers_failed integer,
  containers_running integer,
  cpu_load1 numeric,
  cpu_load15 numeric,
  cpu_load5 numeric,
  database_ok boolean,
  disk_io_read_bytes bigint,
  disk_io_write_bytes bigint,
  disk_total_bytes bigint,
  docker_ok boolean,
  proxy_ok boolean,
  ram_total_bytes bigint,
  uptime_seconds bigint,
  CONSTRAINT node_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT node_metrics_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.node_network_interfaces (
  id uuid NOT NULL,
  node_id uuid NOT NULL,
  name text NOT NULL,
  mac_address text,
  ipv4 text,
  ipv6 text,
  speed_mbps integer,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT node_network_interfaces_pkey PRIMARY KEY (id),
  CONSTRAINT node_network_interfaces_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.nodes(id)
);
CREATE TABLE public.nodes (
  id uuid NOT NULL,
  name text NOT NULL,
  provider text NOT NULL,
  provider_instance_id text,
  public_ip text,
  private_ip text,
  region text,
  status USER-DEFINED NOT NULL DEFAULT 'provisioning'::"NodeStatus",
  roles ARRAY DEFAULT ARRAY[]::text[],
  cpu_cores numeric NOT NULL,
  ram_bytes bigint NOT NULL,
  disk_bytes bigint NOT NULL,
  reserved_cpu numeric NOT NULL DEFAULT 0,
  reserved_ram_bytes bigint NOT NULL DEFAULT 0,
  reserved_disk_bytes bigint NOT NULL DEFAULT 0,
  agent_version text,
  agent_token_hash text,
  last_heartbeat_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  last_connection_at timestamp with time zone,
  last_connection_error text,
  last_connection_status text,
  ssh_host text,
  ssh_key_path text,
  ssh_port integer NOT NULL DEFAULT 22,
  ssh_user text,
  connection_mode text NOT NULL DEFAULT 'ssh'::text,
  ssh_private_key_encrypted text,
  architecture text,
  cpu_model text,
  cpu_threads integer,
  discovery_error text,
  discovery_status USER-DEFINED,
  docker_installed boolean NOT NULL DEFAULT false,
  docker_version text,
  hardware_detected_at timestamp with time zone,
  kernel_version text,
  os_name text,
  os_version text,
  uptime_seconds bigint,
  agent_id text,
  hostname text,
  is_local boolean NOT NULL DEFAULT false,
  is_protected boolean NOT NULL DEFAULT false,
  last_discovered_at timestamp with time zone,
  last_metric_at timestamp with time zone,
  machine_id text,
  node_key text,
  CONSTRAINT nodes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL,
  channel text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  provider text,
  provider_message_id text,
  error_message text,
  attempts integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notification_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT notification_deliveries_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  usage_threshold_email boolean NOT NULL DEFAULT true,
  usage_threshold_in_app boolean NOT NULL DEFAULT true,
  welcome_email boolean NOT NULL DEFAULT true,
  marketing_email boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  project_id uuid,
  resource_type text,
  resource_id uuid,
  type text NOT NULL,
  severity text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  action_label text,
  action_url text,
  idempotency_key text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  read_at timestamp with time zone,
  dismissed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.object_storage_providers (
  id uuid NOT NULL,
  name text NOT NULL,
  provider text NOT NULL,
  endpoint text,
  region text,
  access_key_encrypted text,
  secret_key_encrypted text,
  default_bucket text,
  path_style boolean NOT NULL DEFAULT true,
  public_base_url text,
  local_path text,
  max_storage_bytes bigint,
  current_storage_bytes bigint NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT object_storage_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL,
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL,
  name text NOT NULL,
  owner_user_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'active'::"OrgStatus",
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.password_reset_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  consumed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.plan_features (
  id uuid NOT NULL,
  plan_id uuid NOT NULL,
  feature_key text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT plan_features_pkey PRIMARY KEY (id),
  CONSTRAINT plan_features_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.plan_limits (
  id uuid NOT NULL,
  plan_id uuid NOT NULL,
  max_projects integer,
  max_databases integer,
  max_database_storage_bytes bigint,
  max_object_storage_bytes bigint,
  max_egress_bytes bigint,
  max_vcpu_seconds bigint,
  max_build_vcpu_seconds bigint,
  daily_db_backups integer,
  backup_retention_hours integer,
  max_team_members integer,
  max_custom_domains integer,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  max_storage_buckets integer,
  CONSTRAINT plan_limits_pkey PRIMARY KEY (id),
  CONSTRAINT plan_limits_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.plans (
  id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  price_cents integer NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD'::text,
  billing_interval text NOT NULL DEFAULT 'monthly'::text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::"PlanStatus",
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  description text,
  has_trial boolean NOT NULL DEFAULT false,
  trial_days integer,
  trial_price_cents integer,
  trial_requires_payment_method boolean NOT NULL DEFAULT false,
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL,
  value text NOT NULL,
  description text,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT platform_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_activity_logs (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  actor_user_id uuid,
  action text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT project_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT project_activity_logs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_members (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  invited_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT project_members_pkey PRIMARY KEY (id),
  CONSTRAINT project_members_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'active'::"ProjectStatus",
  region text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.provider_help_docs (
  id uuid NOT NULL,
  slug text NOT NULL,
  provider_key text NOT NULL,
  category text NOT NULL DEFAULT 'object_storage'::text,
  title text NOT NULL,
  summary text,
  body jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT provider_help_docs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.provisioning_policies (
  id uuid NOT NULL,
  resource_type text NOT NULL,
  name text NOT NULL,
  strategy text NOT NULL DEFAULT 'least_used'::text,
  enabled boolean NOT NULL DEFAULT true,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT provisioning_policies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.provisioning_targets (
  id uuid NOT NULL,
  policy_id uuid NOT NULL,
  target_type text NOT NULL,
  target_id uuid NOT NULL,
  priority integer NOT NULL DEFAULT 1,
  weight integer NOT NULL DEFAULT 100,
  enabled boolean NOT NULL DEFAULT true,
  max_usage_percent integer,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT provisioning_targets_pkey PRIMARY KEY (id),
  CONSTRAINT provisioning_targets_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.provisioning_policies(id)
);
CREATE TABLE public.storage_buckets (
  id uuid NOT NULL,
  project_id uuid NOT NULL,
  provider text NOT NULL,
  bucket_name text NOT NULL,
  prefix text,
  region text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::"BucketStatus",
  storage_limit_bytes bigint NOT NULL,
  egress_limit_bytes bigint NOT NULL,
  current_storage_bytes bigint NOT NULL DEFAULT 0,
  current_egress_bytes bigint NOT NULL DEFAULT 0,
  object_storage_provider_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_public boolean NOT NULL DEFAULT false,
  last_synced_at timestamp with time zone,
  object_count bigint NOT NULL DEFAULT 0,
  CONSTRAINT storage_buckets_pkey PRIMARY KEY (id),
  CONSTRAINT storage_buckets_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT storage_buckets_object_storage_provider_id_fkey FOREIGN KEY (object_storage_provider_id) REFERENCES public.object_storage_providers(id)
);
CREATE TABLE public.storage_credentials (
  id uuid NOT NULL,
  bucket_id uuid NOT NULL,
  access_key text NOT NULL,
  encrypted_secret_key text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rotated_at timestamp with time zone,
  CONSTRAINT storage_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT storage_credentials_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES public.storage_buckets(id)
);
CREATE TABLE public.storage_metrics (
  id uuid NOT NULL,
  bucket_id uuid NOT NULL,
  storage_bytes bigint NOT NULL DEFAULT 0,
  object_count bigint,
  network_rx_bytes bigint NOT NULL DEFAULT 0,
  network_tx_bytes bigint NOT NULL DEFAULT 0,
  egress_bytes bigint NOT NULL DEFAULT 0,
  collected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT storage_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT storage_metrics_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES public.storage_buckets(id)
);
CREATE TABLE public.storage_objects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bucket_id uuid NOT NULL,
  key text NOT NULL,
  size_bytes bigint NOT NULL,
  content_type text,
  etag text,
  is_public boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT storage_objects_pkey PRIMARY KEY (id),
  CONSTRAINT storage_objects_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES public.storage_buckets(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL,
  organization_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'active'::"SubscriptionStatus",
  provider text,
  provider_subscription_id text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  billing_phase text NOT NULL DEFAULT 'regular'::text,
  provider_customer_id text,
  regular_price_cents integer,
  trial_end_at timestamp with time zone,
  trial_price_cents integer,
  trial_start_at timestamp with time zone,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.usage_events (
  id uuid NOT NULL,
  organization_id uuid NOT NULL,
  project_id uuid,
  app_id uuid,
  database_id uuid,
  bucket_id uuid,
  usage_type text NOT NULL,
  quantity bigint NOT NULL,
  unit text NOT NULL,
  source_node_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  recorded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deployment_id uuid,
  user_id uuid,
  CONSTRAINT usage_events_pkey PRIMARY KEY (id),
  CONSTRAINT usage_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT usage_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT usage_events_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps(id),
  CONSTRAINT usage_events_database_id_fkey FOREIGN KEY (database_id) REFERENCES public.databases(id),
  CONSTRAINT usage_events_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES public.storage_buckets(id),
  CONSTRAINT usage_events_source_node_id_fkey FOREIGN KEY (source_node_id) REFERENCES public.nodes(id),
  CONSTRAINT usage_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.usage_periods (
  id uuid NOT NULL,
  organization_id uuid NOT NULL,
  subscription_id uuid,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'open'::"UsagePeriodStatus",
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT usage_periods_pkey PRIMARY KEY (id),
  CONSTRAINT usage_periods_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT usage_periods_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.usage_rollups (
  id uuid NOT NULL,
  organization_id uuid NOT NULL,
  project_id uuid,
  usage_period_id uuid NOT NULL,
  usage_type text NOT NULL,
  quantity bigint NOT NULL,
  unit text NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT usage_rollups_pkey PRIMARY KEY (id),
  CONSTRAINT usage_rollups_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT usage_rollups_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT usage_rollups_usage_period_id_fkey FOREIGN KEY (usage_period_id) REFERENCES public.usage_periods(id)
);
CREATE TABLE public.usage_threshold_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  project_id uuid,
  usage_period_id uuid,
  resource_type text NOT NULL,
  threshold_percent integer NOT NULL,
  current_value_bytes bigint,
  limit_value_bytes bigint,
  current_value_seconds bigint,
  limit_value_seconds bigint,
  notification_id uuid,
  email_delivery_id uuid,
  idempotency_key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT usage_threshold_events_pkey PRIMARY KEY (id),
  CONSTRAINT usage_threshold_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT usage_threshold_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT usage_threshold_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT usage_threshold_events_usage_period_id_fkey FOREIGN KEY (usage_period_id) REFERENCES public.usage_periods(id),
  CONSTRAINT usage_threshold_events_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id),
  CONSTRAINT usage_threshold_events_email_delivery_id_fkey FOREIGN KEY (email_delivery_id) REFERENCES public.notification_deliveries(id)
);
CREATE TABLE public.user_auth_accounts (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  provider USER-DEFINED NOT NULL,
  provider_account_id text NOT NULL,
  email text,
  display_name text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at timestamp with time zone,
  CONSTRAINT user_auth_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT user_auth_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  token_hash text NOT NULL,
  ip_address text,
  user_agent text,
  app text NOT NULL DEFAULT 'userapp'::text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp with time zone NOT NULL,
  revoked_at timestamp with time zone,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL,
  name text,
  password_hash text,
  is_platform_admin boolean NOT NULL DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'active'::"UserStatus",
  email_verified boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  auth_provider USER-DEFINED NOT NULL DEFAULT 'password'::"AuthProvider",
  failed_login_count integer NOT NULL DEFAULT 0,
  last_activity_at timestamp with time zone,
  last_login_at timestamp with time zone,
  last_login_ip text,
  password_login_enabled boolean NOT NULL DEFAULT true,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.worker_configs (
  id uuid NOT NULL,
  name text NOT NULL,
  worker_type text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  poll_interval_ms integer NOT NULL,
  concurrency integer NOT NULL,
  lock_timeout_ms integer NOT NULL,
  queues ARRAY DEFAULT ARRAY[]::text[],
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL,
  CONSTRAINT worker_configs_pkey PRIMARY KEY (id)
);